services:
  api:
    build: .
    container_name: flask-api
    entrypoint: []
    command: >
      sh -c "python -m flask --app app run --host=0.0.0.0 --port=5000"
    ports:
      - "5000:5000"
    env_file:
      - path: .env
        required: false
    environment:
      DEBUG_METRICS: "1"
      ENV: development
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: noharm
      DB_USER: postgres
      DB_PASSWORD: postgres
      POTGRESQL_CONNECTION_STRING: postgresql://postgres:postgres@db:5432/noharm
      REPORT_CONNECTION_STRING: postgresql://postgres:postgres@db:5432/noharm
    depends_on:
      db:
        condition: service_healthy
      db-init:
        condition: service_completed_successfully

  db:
    image: postgres:16-alpine
    container_name: nitra_db
    environment:
      POSTGRES_DB: noharm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ${DATABASE_PATH:-./database}:/sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d noharm"]
      interval: 5s
      timeout: 5s
      retries: 10

  db-init:
    image: postgres:16-alpine
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGPASSWORD: postgres
    volumes:
      - ${DATABASE_PATH:-./database}:/sql
    entrypoint: >
      sh -c "
      psql -h db -U postgres -d noharm -f /sql/noharm-public.sql &&
      psql -h db -U postgres -d noharm -f /sql/noharm-create.sql &&
      psql -h db -U postgres -d noharm -f /sql/noharm-newuser.sql &&
      psql -h db -U postgres -d noharm -f /sql/noharm-triggers.sql &&
      psql -h db -U postgres -d noharm -f /sql/noharm-insert.sql
      "

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

volumes:
  postgres_data: