sonar.projectKey=noharm-nutricao_nutricao-backend
sonar.organization=noharm-nutricao
sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/migrations/**,**/.venv/**,**/env/**,**/.git/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
sonar.qualitygate.wait=true
