name: build-validation.yml

on:
  pull_request:
    branches: [develop]

jobs:
  docker-build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo principal
        uses: actions/checkout@v4

      - name: Clonar repo do database
        run: |
          git clone https://github.com/noharm-nutricao/nutricao-database.git database

      - name: Build containers
        run: docker compose -f docker-compose.nitra.yml build

      - name: Subir stack
        run: docker compose -f docker-compose.nitra.yml up -d

      - name: Aguardar API
        run: |
          SUCCESS=false

          for i in {1..40}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/nutritional/healthz)

            echo "Tentativa $i - Status: $STATUS"

            if [ "$STATUS" -eq 200 ]; then
              echo "✅ API pronta!"
              SUCCESS=true
              break
            fi

            sleep 5
          done

          if [ "$SUCCESS" = false ]; then
            echo "⚠️ API não respondeu com 200 em 200s"
            docker compose -f docker-compose.nitra.yml logs
          fi

      - name: Derrubar
        if: always()
        run: docker compose -f docker-compose.nitra.yml down -v
